### ISSUE TITLE
The only test (test_version) fails

### ISSUE THREAD

**Issue by musicinmybrain** [firefly-cpp/NiaAML-GUI#10]
The only test, `test_version`, compares the package version against a hard-coded string that is out of date:

```
____________________________________________________ test_version ____________________________________________________

    def test_version():
>       assert __version__ == '0.1.0'
E       AssertionError: assert '0.1.11' == '0.1.0'
E         - 0.1.0
E         + 0.1.11

tests/test_niaaml_gui.py:5: AssertionError
```

I think this is really just a “placeholder” test, but it doesn’t seem very useful.

**Comment by firefly-cpp** [comment]
Fixed now and enhanced with some tests borrowed from the base NiaAML package.
