### ISSUE TITLE
New ideas

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/NiaAML-GUI#2]
Hi @lukapecnik 

I would like to suggest you a new functionality. 

Please add a CSV browser so that users can check the data as well
as edit data. Users may want to remove some rows or even columns. 

Actually, I believe that one table widget might be the most appropriate solution for this problem.

**Comment by lukapecnik** [comment]
Hi @firefly-cpp,

thank you, great suggestion. I've added this feature to the GUI.
