### ISSUE TITLE
Provide icon

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/NiaAML-GUI#4]
Hi @lukapecnik ,

we are now trying to build a rpm of this package and include this package in Fedora packages. 

Can you please provide also a desktop icon for this package?

You will need to provide:

   - a .desktop file (with an icon would be nice, maybe the fancy one from NiaAML):
https://docs.fedoraproject.org/en-US/packaging-guidelines/#_desktop_files

   - and a Appdata file:
https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/

Do not forget also to publish a release here.

Many thanks for @eclipseo who helps us in preparing a specifications for building a RPM.

**Comment by eclipseo** [comment]
I also suggest you to provide a Makefile to install these files in the right directories. I don't have experience writing one but I suggest defining variables DESTDIR, PREFIX, INSTALL (= install) to set up the correct directories, so that we can use %make_install in the Fedora SPEC:

**Comment by firefly-cpp** [comment]
@lukapecnik, how is the project coming along?

**Comment by musicinmybrain** [comment]
Related: https://github.com/lukapecnik/NiaAML-GUI/pull/9

**Comment by musicinmybrain** [comment]
https://github.com/lukapecnik/NiaAML-GUI/pull/14 implements the suggestion to add an icon file based on the one in NiaAML. It does not include the `Makefile` suggested by @eclipseo, although that’s a good idea.
