### ISSUE TITLE
Library problems

### ISSUE THREAD

**Issue by TomiMilosic** [firefly-cpp/NiaAML-GUI#5]
Hi @lukapecnik! It seems NiaPy has been updated so "from niapy.algorithms.utility import AlgorithmUtility" (optimization_widget.py) won't work anymore. Please fix it as soon as possible ;)
![image](https://user-images.githubusercontent.com/67262025/130331219-5a532f48-75a8-4061-b7be-e45229a30cbf.png)
![image](https://user-images.githubusercontent.com/67262025/130331223-483e2f5b-2aa8-4229-800a-2e8c97ec1a5c.png)

I pasted two pictures for you to easier to solve the problem.

best regards!

**Comment by firefly-cpp** [comment]
@TomiMilosic, could you help us in solving this issue? This task should not be too difficult. You just need to replace current niapy interface with the newest version.
